export default {
   "crust": [
      {
         "id": 1,
         "type":"Normal"
      },
      {
         "id": 2,
         "type":"Thin"
      },
      {
         "id": 3,
         "type":"Chicago Style"
      },
      {
         "id": 4,
         "type":"Garlic"
      },
      {
         "id": 5,
         "type":"Gluten Free"
      },
      {
         "id": 6,
         "type":"Cauliflower"
      },
      {
         "id": 7,
         "type":"Cookie"
      }
   ],
   "sauce":[
      {
         "id": 1,
         "type":"None"
      },
      {
         "id": 2,
         "type":"Marinara"
      },
      {
         "id": 3,
         "type":"Alfredo"
      },
      {
         "id": 4,
         "type":"Buffalo"
      },
      {
         "id": 5,
         "type":"Ranch"
      },
      {
         "id": 6,
         "type":"Pesto"
      },
      {
         "id": 7,
         "type":"Hummus"
      },
      {
         "id": 8,
         "type": "White Garlic Sauce"
      },
      {
         "id": 9,
         "type": "Garlic Ranch Sauce"
      },
      {
         "id": 10,
         "type": "BBQ Sauce"
      },
      {
         "id": 11,
         "type":"Chocolate"
      }

   ],
   "cheese": [
      {
         "id": 1,
         "type":"No Cheese"
      },
      {
         "id": 2,
         "type":"Regular Cheese"  
      },
      {
         "id": 3,
         "type":"Extra Cheese"
      }
   ],
   "meat": [
      {
         "id": 1,
         "type":"Pepperoni"
      },
      {
         "id": 2,
         "type":"Beef"
      },
      {
         "id": 3,
         "type":"Sausage"
      },
      {
         "id": 4,
         "type":"Chicken"
      },
      {
         "id": 5,
         "type":"Bacon"
      },
      {
         "id": 6,
         "type":"Ham"
      },
      {
         "id": 7,
         "type":"None"
      }
   ],
   "toppings":[
      {
         "id": 1,
         "type":"Peppers"
      },
      {
         "id": 2,
         "type":"Onions"
      },
      {
         "id": 3,
         "type":"Jalapenos"
      },
      {
         "id": 4,
         "type": "Banana Peppers"
      },
      {
         "id":5,
         "type": "Mushrooms"
      },
      {
         "id": 6,
         "type":"Broccoli"
      },
      {
         "id": 7,
         "type":"Olives"
      },
      {
         "id": 8,
         "type":"Pineapples"
      },
      {
         "id": 9,
         "type":"Chocolate Chips"
      },
      {
         "id": 10,
         "type":"M&Ms"
      },
      {
         "id":11,
         "type":"Gummy Bears"
      },
      {
         "id": 12,
         "type":"Sprinkles"
      },
      {
         "id": 13,
         "type":"None"
      }
   ],
   "yourpizza": [
     {
      "id": 1,
      "crust": "Garlic",
      "sauce": "Marinara",
      "cheese": "Cheese",
      "meat": "Pepperoni",
      "toppings": "Broccoli"
     },
     {
      "id": 2,
      "crust": "Thin",
      "sauce": "Buffalo",
      "cheese": "Cheese",
      "meat": "Chicken",
      "toppings": "Onions"
     }
   ]
}